import { csvSourceFile } from '../importers/text/csv';
import {
  buildMappingSample,
  guessDelimiter,
  kindSummary,
  MAX_DISTINCT,
  MAX_SAMPLE_ROWS,
} from './sample';
import type { ImportResult } from '../importers/importer';
/** A synthetic export: 3 preamble lines, a header, `rows` data rows. Never real data. */
function syntheticCsv(rows: number): Uint8Array {
  const lines = [
    'Synthetic Exchange — transaction export',
    'Account;demo',
    '',
    'Date;Type;Asset;Amount;TxId;Note',
  ];
  const types = ['Buy', 'Sell', 'Staking Reward', 'Deposit', 'Withdraw'];
  for (let i = 0; i < rows; i += 1) {
    lines.push(
      [
        `2025-01-${String((i % 28) + 1).padStart(2, '0')} 10:00:00`,
        types[i % types.length],
        i % 2 === 0 ? 'BTC' : 'ETH',
        `0.${String(i).padStart(8, '0')}1`,
        `0x${i.toString(16).padStart(64, 'a')}`,
        `note ${i}`,
      ].join(';'),
    );
  }
  return new TextEncoder().encode(lines.join('\n'));
}

const file = (bytes: Uint8Array) =>
  csvSourceFile(
    { id: 'a'.repeat(64), name: 'export_UTC_2_.csv', bytes },
    { delimiter: guessDelimiter(new TextDecoder().decode(bytes)) },
  );

describe('buildMappingSample (F5.14: the sample, never the file)', () => {
  it('sends the first rows including the preamble, not the whole file', () => {
    const sample = buildMappingSample(file(syntheticCsv(1000)), {
      encoding: 'utf-8',
      delimiter: ';',
    });
    expect(sample.rowCount).toBe(1004);
    expect(sample.rows.length).toBeLessThanOrEqual(40);
    expect(sample.rows.length).toBeGreaterThanOrEqual(MAX_SAMPLE_ROWS);
    expect(sample.rows[0]).toEqual(['Synthetic Exchange — transaction export']);
    expect(sample.headerRowGuess).toBe(4);
    expect(sample.rows[3]).toEqual([
      'Date',
      'Type',
      'Asset',
      'Amount',
      'TxId',
      'Note',
    ]);
    expect(sample).toMatchObject({
      fileName: 'export_UTC_2_.csv',
      fileKind: 'csv',
      encoding: 'utf-8',
      delimiter: ';',
    });
    // Row 500 of the file is nowhere in what is sent.
    const json = JSON.stringify(sample);
    expect(json).not.toContain('0.000004991');
    expect(json).not.toContain('note 500');
  });

  it('lists the distinct values of category columns only', () => {
    const sample = buildMappingSample(file(syntheticCsv(300)));
    const columns = Object.fromEntries(
      sample.distinctValues.map((d) => [d.column, d.values]),
    );
    expect(columns['Type']).toEqual([
      'Buy',
      'Deposit',
      'Sell',
      'Staking Reward',
      'Withdraw',
    ]);
    expect(columns['Asset']).toEqual(['BTC', 'ETH']);
    // Amounts, dates, ids and free text are not categories.
    expect(columns['Amount']).toBeUndefined();
    expect(columns['Date']).toBeUndefined();
    expect(columns['TxId']).toBeUndefined();
    expect(columns['Note']).toBeUndefined();
  });

  it('guesses the delimiter over the first lines, not only the preamble', () => {
    expect(guessDelimiter('Statement, demo\nA;B;C\n1;2;3\n4;5;6')).toBe(';');
    expect(guessDelimiter('a,b\n1,2')).toBe(',');
    expect(guessDelimiter('a\tb\n1\t2')).toBe('\t');
  });

  it('drops a column with more than MAX_DISTINCT values', () => {
    const lines = ['Kind,Amount'];
    for (let i = 0; i <= MAX_DISTINCT * 2; i += 1) lines.push(`kind-${i},1`);
    const sample = buildMappingSample(
      file(new TextEncoder().encode(lines.join('\n'))),
    );
    expect(sample.distinctValues).toEqual([]);
  });

  it('samples the fullest sheet of a workbook and names all sheets', () => {
    const sample = buildMappingSample({
      id: 'b'.repeat(64),
      name: 'statement.xlsx',
      kind: 'xlsx',
      sheets: [
        { name: 'Info', rows: [['Generated by demo']] },
        {
          name: 'Data',
          rows: [
            ['Time', 'Operation', 'Coin', 'Change'],
            ['2025-01-01 00:00:00', 'Deposit', 'BTC', '1'],
            [
              '2025-01-02 00:00:00',
              'Simple Earn Flexible Interest',
              'BTC',
              '0.1',
            ],
          ],
        },
      ],
    });
    expect(sample.sheet).toBe('Data');
    expect(sample.sheets).toEqual([
      { name: 'Info', rowCount: 1 },
      { name: 'Data', rowCount: 3 },
    ]);
    expect(sample.encoding).toBeUndefined();
  });
});

describe('kindSummary', () => {
  it('counts kinds and lists the unknown raw types, most frequent first', () => {
    const booking = (kind: string, rawType: string) =>
      ({ kind, rawType }) as unknown as ImportResult['bookings'][number];
    const summary = kindSummary({
      bookings: [
        booking('trade', 'Buy'),
        booking('unknown', 'Reward'),
        booking('unknown', 'Airdrop'),
        booking('unknown', 'Reward'),
      ],
      holdings: [],
      errors: [],
      notes: [],
      period: null,
    });
    expect(summary.kindCounts).toEqual({ trade: 1, unknown: 3 });
    expect(summary.unknownValues).toEqual([
      { value: 'Reward', count: 2 },
      { value: 'Airdrop', count: 1 },
    ]);
  });
});
